language: java

jdk:
  - oraclejdk8

script:
- mvn test
- mvn cobertura:cobertura
- mvn site

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - oracle-java8-installer
